---
- name: Update package
  command: apt update
  when: operation == 'apply'
    
    # Handlers Section
- name: Install apache2
  become: yes
  apt: 
    name: apache2 
    state: present
  when: operation == 'apply'

- name: Python script to write HTML file
  become: yes
  copy:
    content: |
      with open('/var/www/html/index.html', 'w') as f:
          f.write('<html><h1>Hello, world!</h1></html>\n')
    dest: /root/file.py
  when: operation == 'apply'

- name: Run file.py to create HTML file
  become: yes
  command: python3 /root/file.py | sudo tee /var/www/html/index.html
  when: operation == 'apply'

- name: Uninstall apache2
  apt: 
    name: apache2 
    state: absent
  when: operation == 'destroy'
